### ISSUE TITLE
Is it possible to filter four additional location information?

### ISSUE THREAD

**Issue by WWolf** [Mike-Honey/covid-19-genomes#1]
For example, for South Korea, you can easily(?) filter out imported cases in the calculation.

Thank you!

**Comment by Mike-Honey** [comment]
I've only wired up the Country and Location from the source data (GISAID) to the Slicer (filter) control. In some countries (e.g. NZ) a separate Location is shown for imported cases, but not for South Korea.  

In the data for South Korea, the Location is usually blank and it looks like the imported cases are recorded in the "Additional location information" column.  I show that in a table but it is free-form text so a bit tricky to interpret.
